language: node_js
node_js: stable
script:
    - yarn
    - yarn test
    - yarn build

addons:
    chrome: stable

deploy:
  provider: heroku
  api_key:
    secure: GJKxZLbo9u0DU56onslEkGVFbN0FjRuQgRNqHqmSXMZU2jmFkZnYGc/rWfLXRpo8KRkEc/KxxILoXtxeOtCQ1fol7vIFdMcrpcUcuhtTAKLaFQocTe8DdLQ7JfFY+jN1HMkse5RSClJQP3tzCVToLJlQNO43YA5dh0N0dp+Ak4tr+MdMjbqxlfXKO9yNdhBsiVoUNJbpOaXq+F5DHjIpbLv6rqbrvZEtyF8z6FZ9TEN+WWVzob3drTZArd2m53dnPnlasXdIN1TxjTlsO1rAv/JYv3pMRQTrp/ROaM17suqJzX2uFQq0DOBqZ7oHriHuQk6irYZ0kHw2TOFdTe8xbjdhPpwUUjxV81zKZ8I9x7db7yPdjutyGr9C7sj6QzcWaevyq73ni14iiAN397H4gziAf2PjSwksjd2Ys/m7AauImivtpcIO7VzUfCks2CKxXeaURJUxfQL5RZho8fSAGO/OQ8PPXx2QXARJnnhIizwf/0G3/haD7ymx4KrEFyu+FRXxzo3GTaQXemPjru5ucVKQTn8SfuVPvX87MS6SJj7U+0UzyjfZkFFZ8szkOolP64vO0xeGYjGaQ3wQo0WNe8CmYY8uUGP5zIDLfMfP1FZJ9dVU82pzxg88YEPc/aKYMrhAw3FpNSo+GWMs0q3TWjE7oTpw5X/ahS9N7J83uAk=
  app: formv
