language: node_js
node_js: stable
script:
    - yarn
    - yarn test
    - yarn build

addons:
    chrome: stable

deploy:
  provider: heroku
  api_key:
    secure: GngOWXaxIreuywPA/NJk7+YtD1Prev7QVhYGK/dIvZVbtoJWt34ywfR0zT4qybKc+NON/c79x5gc+nOfQiU83Ft6WYSPKYYolAg/VeSrKuo92sWUz8JxYtUDyMkYxZs1JgzKaKedSDLtTgENmlSuSSi7bMw001xrxzcplENGvnlrw8viMtpE1vPZ9Z1W0JV+byAWkXMLNNe/qNVkljGmil1fZK2naXGGtjQLgMVpYRNO/zieTtbK3FFXKrKN+wFnkWej6fIjFEMXvL8unKpVBcKor8hS4dqyq3Pdef6clP7jspWy4YIK9Y2NZbQffCB1vHnfdaME6cdSHmLOhi+3RJNykl01oPucDP7zq5VfZJnUn3sgaKcP8UZNgYjWg1ZrvYSDCNpnOHLtWG1BnuziHF8vnmsidmlJGK9yrH1xbSkMjMYeTPNqRjq2KbsYWgzOcl2tL6OVr7bxTGTeO9l8ERLK2IkIAmK9gtaHsEwk7tj6uhICEkvz9MuPAlVDEFsuJPQkK6X6bpaMKX/4+GqwC5Bv+r14uUMWIyPLdbgFSukx7kRh7ibJPHbnuJNrN5G0IWjPhTVc/n3pu6Uu1mzrd1aq9lMQqY0/jGQbupPWV3UnvKvU/JCl9nDQ51BOtDJcB2KeGz5I7bQ3V3WXzRbEIiL3GruBhFkR9WwKgrN2xZs=
  app: formv
  on:
    repo: Wildhoney/Formv
