language: node_js
node_js: stable
script:
    - yarn
    - yarn test
    - yarn build

addons:
    chrome: stable

deploy:
    provider: heroku
    api_key:
        secure: bR1xG4lJENcfPAcIwI97FfvExHoF+xVKtF78PSfI9ZzOuqHIMjq/VEBVidPRj3BapCWPPThHLGWy9hUL8ahUavdoHxcqN2Z/qATVvIZmduvo4+TrAPFh8yP/tC09kn9M+VFb5hDKqI0reCOpxXVP+ax1HxGAAV+E8tB3DIEvC6zZyKWpgVdQcUbn8fkSov3MALdUPLnRWRLW18X19F5s+wI+q1DvPGIKnGN2zKy2IlZ9m2Yr79mIMbehvZlJytFMaduY41fXkZThNCd1Ze1LW07+l5bfseUyvV6XLhEbqJsOi6FR708qA0Rl8Jc2zlFw0TFZFQDMd7afmsMAUAgQDwyNwOywqcJ5zSK+fTeRsDZ4/lxeLpIfW9naLRnNr6ZOV/FhELbQ55VBsnm13hoK/9cVKdQeSP4jLwys53H33zpH9u1IutRueUZzdjLnCUYcKcmRE9GYIrStT7JtTW6SRK0CvXcXQ7pGyt9tmEE1RrMZgBoB8Pxq1EVhZdBD80eKQakff/f62C7CqoF92IXXdK6ucaaaDWTdQJ4CHfVZCEceGDpJQqp1pzJ7FnXRh2vQbGLbAtw9/Ihc/RVHYAKi5VoSqIsVX5XyoJ7vc/UKFjf359lZEpTMF/wYy2lpm8DZw+odzMmp2Mgfd1GCnZA1PbsibST+p6RdzUFSKyg9KFI=
    app: formv
    on:
        repo: Wildhoney/Formv
