language: node_js
node_js: stable
script:
    - yarn
    - yarn test
    - yarn build

addons:
    chrome: stable

deploy:
  provider: heroku
  api_key:
    secure: qyX7r++5+zppTXokv79WUeo9CN1+OykRCVxFylkVWDejdIhJ9u0Iol4lkVcMUst3c+OrJlj2OZIaruAKVm3a4hhjkRlcuQDQwfbkZUefmCp/bztRLunTzxNhVscnzUb6R54u5GedvsflntpPraUXUJWgX6ndQGbjrxRMHGCY7Nw6baYcNwk1ufbtJYJWNhmmALD9EEUXW3LDUvD+cM/UsA82lFlD/JZm+C2Nv7FWdplJwkpWuapG2ERWOf5JUBhr2Jf1yqnknxkvsiMoG9EjlFeIj4QkMIj5c7KQC1z9Wf9ZgCi4EmhLl1FQYg/2ov6Vl6Fr4w8RrjKNcWfJqV9mOmKhQQphsbwI7/2OU18yu/g2fTcubrsUpq/Qx/qoo0yC9VMLn3JxOyHaijkACLuG+izkL09KoGzr7b+eLNJhvK11VEVQYSqpScPOsSCqjPqSZdFl0RBvDfuTRseQeR11Mly4bXU/epgtjJ82sg2HKaa1KVz/+CCapx7+CnIlKJjClc6Cqzafv8ps7hySRYT+zRCMtvK8DpBQVGdFrWKDvqKAlOvE5g9v3lem/ldHrZgKPlYCFsu/ri3/owEi7TPbHLZI+u7ZTJa0zexl5KGrflALl5WXHRrEHZ3Q/Kvec2m9QQ/jWY3JuuT/eaw64RHcsNc0xfiy5rFUqFkm5eSXK9A=
  app: formv
  on:
    repo: Wildhoney/Formv
